/**
 * 红色
 */
interface GeneratedObjectLiteralInterface_1 {
  BASE: string;
}

export const COLOR_RED: GeneratedObjectLiteralInterface_1 = {
  BASE: '#F56C6C'
};

/**
 * 红色
 */
export const COLOR_GRAY: GeneratedObjectLiteralInterface_1 = {
  BASE: '#969799'
};

/**
 * 置灰的颜色
 */
interface GeneratedObjectLiteralInterface_2 {
  VERY_MINI: string;
  MINI: string;
  BASE: string;
  MEDIUM: string;
}

export const DISABLE_COLOR: GeneratedObjectLiteralInterface_2 = {
  VERY_MINI: 'rgba(223,223,223,0.15)',
  MINI: 'rgba(56,65,83,0.5)',
  BASE: '#f2f3f7',
  MEDIUM: '#3E5071'
};

/**
 * 置灰的颜色
 */
export const BACKGROUND_COLOR:GeneratedObjectLiteralInterface_1 = {
  BASE: '#F7F8FA'
};

/**
 * 布局宽度和高度
 */
interface GeneratedObjectLiteralInterface_3 {
  TWELVE: string;
  TWO: string;
  THIRTY: string;
  FORTY_TWO: string;
  FORTY_FOUR: string;
  SIXTY: string;
  SIXTY_FIVE: string;
  SEVENTY_NINE: string;
  EIGHTY: string;
  NINETY: string;
  THREE_HUNDRED: string;
  ONE_HUNDRED_AND_FIFTY: string;
  ONE_HUNDRED_AND_TWENTY: string;
  FULL: string;
  SIX_HUNDRED: string;
  EIGHT_HUNDRED: string;
  SIX_HUNDRED_AND_SIXTY: string;
  THREE_HUNDRED_AND_THIRTY_SEVEN: string;
  THREE_HUNDRED_AND_SIXTY_SEVEN: string;
  FOUR_HUNDRED_AND_SIXTY_FIVE: string;
  TWO_HUNDRED: string;
  TWO_HUNDRED_AND_FIFTY: string;
  ONE_HUNDRED_AND_SEVENTY_FIVE: string;
  THREE_HUNDRED_AND_NINETY_FIVE: string;
  TWO_HUNDRED_AND_EIGHTY_FIVE: string;
  THREE_HUNDRED_AND_EIGHTY_TWO: string;
}

export const CONTAINER_SIZE: GeneratedObjectLiteralInterface_3 = {
  TWELVE: '12lpx',
  TWO: '2lpx',
  THIRTY: '30lpx',
  FORTY_TWO: '42lpx',
  FORTY_FOUR: '44lpx',
  SIXTY: '60lpx',
  SIXTY_FIVE: '65lpx',
  SEVENTY_NINE: '79lpx',
  EIGHTY: '80lpx',
  NINETY: '90lpx',
  THREE_HUNDRED: '300lpx',
  ONE_HUNDRED_AND_FIFTY: '150lpx',
  ONE_HUNDRED_AND_TWENTY: '120lpx',
  FULL: '100%',
  SIX_HUNDRED: '600lpx',
  EIGHT_HUNDRED: '800lpx',
  SIX_HUNDRED_AND_SIXTY: '660lpx',
  THREE_HUNDRED_AND_THIRTY_SEVEN: '337lpx',
  THREE_HUNDRED_AND_SIXTY_SEVEN: '367lpx',
  FOUR_HUNDRED_AND_SIXTY_FIVE: '465lpx',
  TWO_HUNDRED: '200lpx',
  TWO_HUNDRED_AND_FIFTY: '250lpx',
  ONE_HUNDRED_AND_SEVENTY_FIVE: '175lpx',
  THREE_HUNDRED_AND_NINETY_FIVE: '395lpx',
  TWO_HUNDRED_AND_EIGHTY_FIVE: '285lpx',
  THREE_HUNDRED_AND_EIGHTY_TWO: '182lpx'
};

/**
 * 颜色
 */
interface GeneratedObjectLiteralInterface_4 {
  PLACEHOLDER: string;
  TEXT: string;
  CANCEL_BTN: string;
  MINI: string;
  SMALL: string;
  BASE: string;
  MEDIUM: string;
  LARGE: string;
}

export const COLOR_BLUE: GeneratedObjectLiteralInterface_4 = {
  PLACEHOLDER: 'rgba(62,80,113,0.45)',
  TEXT: '#006AE9',
  CANCEL_BTN: '#F2F4FF',
  MINI: '#4B72EF',
  SMALL: '#49689B',
  BASE: '#3E5071',
  MEDIUM: '#30405D',
  LARGE: '#304B78'
};

/**
 * 间距样式
 */
interface GeneratedObjectLiteralInterface_5 {
  SEVEN: string;
  FIVE: string;
  MINI: string;
  TWENTY: string;
  SMALL: string;
  BASE: string;
  MEDIA: string;
  LARGE: string;
  EIGHTY: string;
  EIGHTY_EIGHT: string;
  TWENTY_FIVE: string;
  THIRTY: string;
  THIRTY_SEVEN: string;
  SIXTY: string;
  THREE_HUNDRED: string;
  ONE_HUNDRED_AND_SIXTY: string;
  FIFTY: string;
}

export const SPACE: GeneratedObjectLiteralInterface_5 = {
  SEVEN: '7lpx',
  FIVE: '5lpx',
  MINI: '10lpx',
  TWENTY: '20lpx',
  SMALL: '16lpx',
  BASE: '22lpx',
  MEDIA: '36lpx',
  LARGE: '44lpx',
  EIGHTY: '80lpx',
  EIGHTY_EIGHT: '88lpx',
  TWENTY_FIVE: '25lpx',
  THIRTY: '30lpx',
  THIRTY_SEVEN: '37lpx',
  SIXTY: '60lpx',
  THREE_HUNDRED: '300lpx',
  ONE_HUNDRED_AND_SIXTY: '160lpx',
  FIFTY: '50lpx'
};

/**
 * 文字大小
 */
interface GeneratedObjectLiteralInterface_6 {
  MINI: string;
  SMALL: string;
  BASE: string;
  MEDIUM: string;
  LARGE: string;
  VERY_LARGE: string;
  THIRTY: string;
  THIRTY_THREE: string;
}

export const FONT_SIZE: GeneratedObjectLiteralInterface_6 = {
  MINI: '24lpx',
  SMALL: '26lpx',
  BASE: '28lpx',
  MEDIUM: '32lpx',
  LARGE: '36lpx',
  VERY_LARGE: '44lpx',
  THIRTY: '30lpx',
  THIRTY_THREE: '33lpx'
};

/**
 * 文字大小
 */
interface GeneratedObjectLiteralInterface_7 {
  NORMAL: number;
  LIGHTER: number;
  REGULAR: number;
  MEDIUM: number;
  BOLD: number;
  BOLDER: number;
}

export const FONT_WEIGHT: GeneratedObjectLiteralInterface_7 = {
  NORMAL: FontWeight.Normal as number,
  LIGHTER: FontWeight.Lighter as number,
  REGULAR: FontWeight.Regular as number,
  MEDIUM: FontWeight.Medium as number,
  BOLD: FontWeight.Bold as number,
  BOLDER: FontWeight.Bolder as number
};

/**
 * 行高
 */
interface GeneratedObjectLiteralInterface_8 {
  BASE: string;
  MEDIUM: string;
  FORTY_FOUR: string;
  SIXTY: string;
  SIXTY_SIX: string;
  FIFTY_ONE: string;
}

export const LINE_HEIGHT: GeneratedObjectLiteralInterface_8 = {
  BASE: '30lpx',
  MEDIUM: '40lpx',
  FORTY_FOUR: '44lpx',
  SIXTY: '60lpx',
  SIXTY_SIX: '66lpx',
  FIFTY_ONE: '51lpx'
};

/**
 * 圆边距
 */
interface GeneratedObjectLiteralInterface_9 {
  BASE: string;
  MEDIUM: string;
  LARGE: string;
  VERY_LARGE: string;
}

export const BORDER_RADIUS: GeneratedObjectLiteralInterface_9 = {
  BASE: '15lpx',
  MEDIUM: '18lpx',
  LARGE: '22lpx',
  VERY_LARGE: '60lpx'
};

/**
 * 边框宽度
 */
export const BORDER_WIDTH:GeneratedObjectLiteralInterface_1 = {
  BASE: '1.85lpx'
};

/**
 * 获取lpx单位中的数字
 * @param styleText
 * @returns
 */
export function getLpxNum(styleText: string) {
  return Number(styleText.replace(/[^\d\.]/g, ''));
}